name: "Code Quality"

on:
  push:
  pull_request:

jobs:
  lint-and-format:
    name: "ShellCheck & shfmt"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts'

      - name: Setup shfmt
        run: sudo apt-get install -y shfmt

      - name: Run shfmt (Check Formatting)
        run: shfmt -i 2 -ci -d scripts/*/*.sh
